import { useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, CalendarDays, Check, ChevronRight, Clock3, LayoutDashboard, MessageCircle, Play, ShieldCheck, Sparkles, Target, TimerReset, X } from 'lucide-react';
import { sections, semester, periodLabels, type Section } from '@/data/timetables';
import { addDays, calculateProjectedAttendance, dateLabel, getClassesBetweenDates, getSubjectClassesBetweenDates, maximumAchievable, metricFor, overallRecord, percentage, requiredForTarget, statusFor, todayString, type AttendanceMap, type ClassInstance } from '@/engine/attendance';
import './index.css';

type View = 'dashboard' | 'timetable' | 'calculator' | 'simulator' | 'leave' | 'analytics' | 'advisor';
const initialRecords: AttendanceMap = Object.fromEntries(sections[0].subjects.map((item, index) => [item.code, { attended: index % 3 === 0 ? 0 : 0, conducted: 0 }]));
const nav: { id: View; label: string; icon: typeof LayoutDashboard }[] = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { id: 'timetable', label: 'Timetable', icon: CalendarDays }, { id: 'calculator', label: 'Calculator', icon: Target }, { id: 'simulator', label: 'What-If', icon: TimerReset }, { id: 'leave', label: 'Leave', icon: ShieldCheck }, { id: 'analytics', label: 'Analytics', icon: BarChart3 }, { id: 'advisor', label: 'Advisor', icon: MessageCircle },
];
const clampRecord = (attended: string, conducted: string) => { const c = Math.max(0, Number(conducted) || 0); return { conducted: c, attended: Math.min(c, Math.max(0, Number(attended) || 0)) }; };

function App() {
  const [view, setView] = useState<View>('dashboard');
  const [sectionCode, setSectionCode] = useState(sections[0].code);
  const [codeInput, setCodeInput] = useState(sections[0].code);
  const [sectionError, setSectionError] = useState('');
  const [records, setRecords] = useState<AttendanceMap>(initialRecords);
  const [planningDate, setPlanningDate] = useState(semester.endDate);
  const [filter, setFilter] = useState<'All' | 'SAFE' | 'CAUTION' | 'DANGER'>('All');
  const [selectedClass, setSelectedClass] = useState<ClassInstance | null>(null);
  const [chatOpen, setChatOpen] = useState(false);
  const [question, setQuestion] = useState('');
  const [messages, setMessages] = useState<{ from: 'user' | 'advisor'; text: string }[]>([]);
  const section = sections.find((item) => item.code === sectionCode) ?? sections[0];
  const today = todayString();
  const boundedToday = today < semester.startDate ? semester.startDate : today > semester.endDate ? semester.endDate : today;
  const isBefore = today < semester.startDate;
  const isAfter = today > semester.endDate;
  const remainingEnd = isAfter ? semester.endDate : semester.endDate;
  const remainingClasses = useMemo(() => getClassesBetweenDates(section, boundedToday, remainingEnd), [section, boundedToday, remainingEnd]);
  const plannedClasses = useMemo(() => getClassesBetweenDates(section, boundedToday, planningDate < boundedToday ? boundedToday : planningDate), [section, boundedToday, planningDate]);
  const metrics = useMemo(() => section.subjects.map((subject) => ({ subject, metric: metricFor(records[subject.code] ?? { attended: 0, conducted: 0 }, remainingClasses.filter((item) => item.subject.code === subject.code).length) })), [section, records, remainingClasses]);
  const overall = overallRecord(section.subjects, records);
  const overallPct = percentage(overall.attended, overall.conducted);
  const overallStatus = statusFor(overallPct);
  const healthCounts = { safe: metrics.filter((x) => statusFor(x.metric.percentage) === 'SAFE').length, caution: metrics.filter((x) => statusFor(x.metric.percentage) === 'CAUTION').length, danger: metrics.filter((x) => statusFor(x.metric.percentage) === 'DANGER').length };

  const updateRecord = (code: string, attended: string, conducted: string) => setRecords((current) => ({ ...current, [code]: clampRecord(attended, conducted) }));
  const selectSection = () => { const found = sections.find((item) => item.code.toLowerCase() === codeInput.trim().toLowerCase()); if (!found) { setSectionError('Section code not found in the supplied timetable dataset.'); return; } setSectionError(''); setSectionCode(found.code); setRecords(Object.fromEntries(found.subjects.map((item) => [item.code, { attended: 0, conducted: 0 }]))); };
  const askAdvisor = (text: string) => { if (!text.trim()) return; const answer = advisorAnswer(text.trim(), section, records, remainingClasses, today); setMessages((current) => [...current, { from: 'user', text: text.trim() }, { from: 'advisor', text: answer }]); setQuestion(''); };

  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><Activity size={21} /></div><div><strong>ATTENDANCE</strong><span>PREDICTOR</span></div></div><div className="sidebar-label">Workspace</div><nav>{nav.map(({ id, label, icon: Icon }) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => setView(id)}><Icon size={18} /><span>{label}</span>{id === 'advisor' && <span className="nav-dot" />}</button>)}</nav><div className="sidebar-footer"><div className="mini-status"><span className="pulse" /> System ready</div><span className="source-note">Source: supplied timetable<br />Odd semester · 2026–27</span></div></aside>
    <main className="main"><header className="topbar"><div className="mobile-brand"><div className="brand-mark"><Activity size={18} /></div><strong>ATTENDANCE PREDICTOR</strong></div><div className="topbar-meta"><span className="live-dot" /> Live planning mode <span className="top-divider" /> Today <b>{dateLabel(today)}</b></div><button className="advisor-top" onClick={() => { setChatOpen(true); setView('advisor'); }}><Sparkles size={16} /> Ask advisor</button></header>
      <div className="content"><section className="page-heading"><div><p className="eyebrow">COMMAND CENTER / {section.year}</p><h1>{viewTitle(view)}</h1><p className="muted">{viewSubtitle(view, section, isBefore, isAfter)}</p></div><div className="section-picker"><label>Selected section</label><div className="picker-row"><select value={sectionCode} onChange={(e) => { setSectionCode(e.target.value); setCodeInput(e.target.value); }} aria-label="Selected timetable section">{sections.map((item) => <option key={item.code} value={item.code}>{item.displayName} · {item.code}</option>)}</select><input value={codeInput} onChange={(e) => setCodeInput(e.target.value)} aria-label="Enter section code" placeholder="Section code" /><button className="icon-button primary" onClick={selectSection} aria-label="Load section"><ChevronRight size={17} /></button></div>{sectionError && <span className="field-error">{sectionError}</span>}</div></section>
      {view === 'dashboard' && <Dashboard section={section} metrics={metrics} overall={overall} overallPct={overallPct} overallStatus={overallStatus} healthCounts={healthCounts} plannedClasses={plannedClasses} planningDate={planningDate} setPlanningDate={setPlanningDate} filter={filter} setFilter={setFilter} setView={setView} setSelectedClass={setSelectedClass} updateRecord={updateRecord} remainingClasses={remainingClasses} isBefore={isBefore} isAfter={isAfter} />}
      {view === 'timetable' && <Timetable section={section} onSelect={setSelectedClass} />}
      {view === 'calculator' && <Calculator section={section} metrics={metrics} records={records} remainingClasses={remainingClasses} />}
      {view === 'simulator' && <Simulator section={section} records={records} remainingClasses={remainingClasses} />}
      {view === 'leave' && <LeaveSimulator section={section} records={records} today={boundedToday} />}
      {view === 'analytics' && <Analytics section={section} metrics={metrics} overallPct={overallPct} overall={overall} />}
      {view === 'advisor' && <Advisor messages={messages} question={question} setQuestion={setQuestion} askAdvisor={askAdvisor} />}
      </div>
    </main>
    <button className="floating-advisor" onClick={() => setChatOpen((open) => !open)}><Sparkles size={18} /><span>AI Attendance Advisor</span></button>
    {chatOpen && <div className="chat-popover"><div className="chat-head"><div><b>Attendance Advisor</b><span>Uses your live dashboard state</span></div><button onClick={() => setChatOpen(false)}><X size={17} /></button></div><div className="chat-messages">{messages.length === 0 ? <div className="chat-empty"><Sparkles size={25} /><b>Ask about your attendance</b><span>Try “Can I miss tomorrow?” or “Can I reach 90%?”</span></div> : messages.slice(-4).map((message, index) => <div key={index} className={`chat-message ${message.from}`}>{message.text}</div>)}</div><div className="quick-prompts">{['Can I miss tomorrow?', 'Can I reach 90%?', 'Which subjects are at risk?'].map((prompt) => <button key={prompt} onClick={() => askAdvisor(prompt)}>{prompt}</button>)}</div><div className="chat-input"><input value={question} onChange={(e) => setQuestion(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && askAdvisor(question)} placeholder="Ask a question..." /><button onClick={() => askAdvisor(question)}><ChevronRight size={18} /></button></div></div>}
    {selectedClass && <div className="modal-backdrop" onClick={() => setSelectedClass(null)}><div className="detail-modal" onClick={(e) => e.stopPropagation()}><button className="modal-close" onClick={() => setSelectedClass(null)}><X size={18} /></button><span className="class-kicker">{selectedClass.sessionType === 'lab' ? 'Laboratory session' : 'Scheduled class'}</span><h2>{selectedClass.subject.name}</h2><p className="modal-code">{selectedClass.subject.code}</p><div className="detail-grid"><Detail label="Date" value={`${selectedClass.day}, ${dateLabel(selectedClass.date)}`} /><Detail label="Time" value={`${selectedClass.startTime} – ${selectedClass.endTime}`} /><Detail label="Period" value={`Period ${selectedClass.period}`} /><Detail label="Room" value={selectedClass.room ?? section.venue ?? 'Not specified in source'} /><Detail label="Faculty" value={selectedClass.subject.faculty ?? 'Not specified in source'} /><Detail label="Type" value={selectedClass.sessionType === 'lab' ? 'Lab' : 'Lecture'} /></div></div></div>}
  </div>;
}

function Dashboard({ section, metrics, overall, overallPct, overallStatus, healthCounts, plannedClasses, planningDate, setPlanningDate, filter, setFilter, setView, setSelectedClass, updateRecord, remainingClasses, isBefore, isAfter }: any) {
  const visible = metrics.filter((item: any) => filter === 'All' || statusFor(item.metric.percentage) === filter);
  const upcoming = plannedClasses.slice(0, 4);
  return <>
    {isAfter && <div className="notice warning"><AlertTriangle size={18} /><div><b>Semester ended</b><span>The semester ended on {dateLabel(semester.endDate)}. Historical calculations remain available; no future classes are generated.</span></div></div>}
    {isBefore && <div className="notice info"><CalendarDays size={18} /><div><b>Semester starts {dateLabel(semester.startDate)}</b><span>Enter your current attendance and plan ahead. Future classes are calculated from the supplied timetable.</span></div></div>}
    <div className="hero-grid"><div className="hero-card"><div className="hero-card-top"><span className="eyebrow light">OVERALL ATTENDANCE</span><span className={`status-pill ${overallStatus.toLowerCase()}`}>{overallStatus}</span></div><div className="hero-number">{overall.conducted ? overallPct.toFixed(1) : '—'}<span>%</span></div><p>{overall.conducted ? `${overall.attended} attended out of ${overall.conducted} conducted classes` : 'Enter exact attendance below to start calculating'}</p><div className="progress-track"><div className="progress-fill" style={{ width: `${Math.min(overallPct, 100)}%` }} /></div><div className="hero-foot"><span>75% threshold</span><span>90% target</span></div></div><div className="stats-stack"><Stat label="Classes conducted" value={overall.conducted} icon={<CalendarDays size={17} />} /><Stat label="Classes remaining" value={remainingClasses.length} icon={<Clock3 size={17} />} /><Stat label="Need attention" value={healthCounts.caution + healthCounts.danger} icon={<AlertTriangle size={17} />} accent /></div></div>
    <div className="section-row"><div><p className="eyebrow">YOUR PLAN</p><h2>Plan with confidence</h2></div><div className="date-plan"><label htmlFor="planning-date">Planning until</label><input id="planning-date" type="date" min={semester.startDate} max={semester.endDate} value={planningDate} onChange={(e) => setPlanningDate(e.target.value)} /><button className="secondary-button" onClick={() => setPlanningDate(semester.endDate)}>Plan to semester end</button></div></div>
    <div className="insight-grid"><div className="insight-card"><div className="insight-icon green"><ShieldCheck size={18} /></div><div><b>{healthCounts.safe} subjects safe</b><span>At or above 90% right now</span></div></div><div className="insight-card"><div className="insight-icon amber"><Target size={18} /></div><div><b>{healthCounts.caution} subjects need attention</b><span>Between 75% and 90%</span></div></div><div className="insight-card"><div className="insight-icon red"><AlertTriangle size={18} /></div><div><b>{healthCounts.danger} subjects below 75%</b><span>Review detention protection</span></div></div></div>
    <div className="section-row subjects-row"><div><p className="eyebrow">SUBJECT HEALTH</p><h2>Attendance by subject</h2></div><div className="filter-tabs">{(['All', 'SAFE', 'CAUTION', 'DANGER'] as const).map((item) => <button key={item} className={filter === item ? 'selected' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div></div>
    <div className="subject-grid">{visible.map(({ subject, metric }: any) => <SubjectCard key={subject.code} subject={subject} metric={metric} setView={setView} setSelectedClass={setSelectedClass} updateRecord={updateRecord} remainingClasses={remainingClasses} />)}</div>
    <div className="section-row upcoming-row"><div><p className="eyebrow">UPCOMING CLASSES</p><h2>Next in your schedule</h2></div><button className="text-button" onClick={() => setView('timetable')}>View timetable <ChevronRight size={15} /></button></div><div className="upcoming-list">{upcoming.length ? upcoming.map((item: ClassInstance) => <button key={`${item.date}-${item.period}-${item.subject.code}`} className="upcoming-item" onClick={() => setSelectedClass(item)}><div className="date-block"><b>{new Date(`${item.date}T12:00:00`).toLocaleDateString('en-IN', { day: '2-digit' })}</b><span>{new Date(`${item.date}T12:00:00`).toLocaleDateString('en-IN', { month: 'short' })}</span></div><div className="upcoming-info"><b>{item.subject.name}</b><span>{item.day} · {item.startTime}–{item.endTime}</span></div><span className="subject-code">{item.subject.code}</span><ChevronRight size={16} /></button>) : <Empty text="No upcoming classes in the selected period." />}</div>
  </>;
}
function SubjectCard({ subject, metric, setView, setSelectedClass, updateRecord, remainingClasses }: any) { const status = statusFor(metric.percentage); return <article className="subject-card"><div className="subject-card-head"><div><span className="subject-tag">{subject.code}</span><h3>{subject.name}</h3></div><span className={`status-pill ${status.toLowerCase()}`}>{status}</span></div><div className="subject-percent"><b>{metric.conducted ? metric.percentage.toFixed(1) : '—'}<small>%</small></b><span>{metric.attended} / {metric.conducted} attended</span></div><div className="mini-progress"><div className={`mini-fill ${status.toLowerCase()}`} style={{ width: `${Math.min(metric.percentage, 100)}%` }} /></div><div className="metric-lines"><div><span>Remaining</span><b>{metric.remaining}</b></div><div><span>Safe absences · 75%</span><b>{metric.recovery75 ? metric.safeAbsences75 : '—'}</b></div><div><span>Need to reach · 90%</span><b>{metric.recovery90 ? metric.required90 : 'Unreachable'}</b></div><div><span>Max achievable</span><b>{metric.maxAchievable.toFixed(1)}%</b></div></div><div className="subject-actions"><button onClick={() => setView('simulator')}><Play size={14} /> Simulate</button><button onClick={() => setView('calculator')}>Plan <ChevronRight size={14} /></button><button aria-label="View timetable" onClick={() => { const first = remainingClasses.find((item: ClassInstance) => item.subject.code === subject.code); if (first) setSelectedClass(first); else setView('timetable'); }}><CalendarDays size={14} /></button></div><div className="entry-row"><label>Attended <input type="number" min="0" value={metric.attended} onChange={(e) => updateRecord(subject.code, e.target.value, String(metric.conducted))} /></label><label>Conducted <input type="number" min="0" value={metric.conducted} onChange={(e) => updateRecord(subject.code, String(metric.attended), e.target.value)} /></label></div></article>; }
function Stat({ label, value, icon, accent }: any) { return <div className={`stat-card ${accent ? 'accent' : ''}`}><div className="stat-icon">{icon}</div><div><span>{label}</span><b>{value}</b></div></div>; }
function Timetable({ section, onSelect }: { section: Section; onSelect: (item: ClassInstance) => void }) { const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']; return <div className="panel timetable-panel"><div className="panel-intro"><div><span className="eyebrow">SOURCE-BACKED SCHEDULE</span><h2>{section.displayName} <span className="code-chip">{section.code}</span></h2><p>{section.year} · {section.semester} · Venue: {section.venue ?? 'Not specified in source'}</p></div><span className="source-badge"><Check size={14} /> Verified from supplied PDF</span></div><div className="timetable-scroll"><div className="timetable-grid"><div className="time-cell grid-head">Time</div>{days.map((day) => <div className="day-head grid-head" key={day}>{day}</div>)}{Object.entries(periodLabels).map(([period, [start, end]]) => <div className="time-cell" key={period}><b>{start}</b><span>{end}</span></div>)}{Object.entries(periodLabels).flatMap(([period]) => days.map((day) => { const entry = section.weeklySchedule.find((item) => item.day === day && item.period === Number(period)); const sub = entry && section.subjects.find((item) => item.slot === entry.slot); return <button key={`${day}-${period}`} className={`time-slot ${entry?.sessionType === 'lab' ? 'lab' : ''} ${!entry ? 'empty' : ''}`} disabled={!entry || !sub} onClick={() => entry && sub && onSelect({ ...entry, date: '', subject: sub })}>{sub ? <><b>{sub.code}</b><span>{sub.name}</span>{entry?.sessionType === 'lab' && <em>LAB</em>}</> : <span>—</span>}</button>; }))}</div></div><div className="legend"><span><i className="legend-dot lecture" /> Lecture</span><span><i className="legend-dot lab" /> Laboratory</span><span>Click any class for details</span></div></div>; }
function Calculator({ section, metrics, records, remainingClasses }: any) { const [target, setTarget] = useState(75); return <div><div className="section-row"><div><p className="eyebrow">ATTENDANCE CALCULATOR</p><h2>How many classes can I miss?</h2><p className="muted">Every number is calculated from your exact attendance and the selected section’s actual remaining timetable.</p></div><div className="target-toggle"><span>Target</span>{[75, 90].map((value) => <button key={value} className={target === value ? 'selected' : ''} onClick={() => setTarget(value)}>{value}%</button>)}</div></div><div className="calc-overview"><div><span>Threshold selected</span><b>{target}%</b></div><div><span>Total remaining classes</span><b>{remainingClasses.length}</b></div><div><span>Subjects below target</span><b>{metrics.filter((item: any) => item.metric.percentage < target).length}</b></div></div><div className="calculator-list">{metrics.map(({ subject, metric }: any) => { const req = requiredForTarget(records[subject.code] ?? { attended: 0, conducted: 0 }, metric.remaining, target); const can = req <= metric.remaining; return <div className="calc-row" key={subject.code}><div className="calc-subject"><span className={`risk-bar ${statusFor(metric.percentage).toLowerCase()}`} /><div><b>{subject.name}</b><span>{subject.code} · Current {metric.conducted ? metric.percentage.toFixed(1) : '—'}%</span></div></div><div className="calc-value"><span>Must attend</span><b>{can ? req : '—'}</b></div><div className="calc-value"><span>Safe absences</span><b>{can ? metric.remaining - req : '0'}</b></div><div className={`recovery-label ${can ? 'possible' : 'impossible'}`}>{can ? 'RECOVERY POSSIBLE' : 'TARGET UNREACHABLE'}</div></div>; })}</div></div>; }
function Simulator({ section, records, remainingClasses }: any) { const [subjectCode, setSubjectCode] = useState(section.subjects[0].code); const [attend, setAttend] = useState(5); const [miss, setMiss] = useState(1); const subject = section.subjects.find((item: any) => item.code === subjectCode) ?? section.subjects[0]; const record = records[subject.code] ?? { attended: 0, conducted: 0 }; const current = percentage(record.attended, record.conducted); const projected = calculateProjectedAttendance(record, attend, attend + miss); const afterRemaining = Math.max(0, remainingClasses.filter((item: ClassInstance) => item.subject.code === subject.code).length - attend - miss); return <div><div className="section-row"><div><p className="eyebrow">WHAT-IF SIMULATOR</p><h2>Attendance What-If</h2><p className="muted">Model a plan without changing your saved attendance.</p></div><span className="scenario-badge"><TimerReset size={15} /> Live scenario</span></div><div className="simulator-layout"><div className="panel form-panel"><label>Subject<select value={subjectCode} onChange={(e) => setSubjectCode(e.target.value)}>{section.subjects.map((item: any) => <option key={item.code} value={item.code}>{item.name}</option>)}</select></label><label>Upcoming classes to attend<input type="number" min="0" max={remainingClasses.length} value={attend} onChange={(e) => setAttend(Math.max(0, Number(e.target.value) || 0))} /></label><label>Upcoming classes to miss<input type="number" min="0" max={remainingClasses.length} value={miss} onChange={(e) => setMiss(Math.max(0, Number(e.target.value) || 0))} /></label><div className="range-row"><span>Attend {attend}</span><input type="range" min="0" max={Math.max(10, remainingClasses.length)} value={attend} onChange={(e) => setAttend(Number(e.target.value))} /></div></div><div className="projection-card"><span className="eyebrow light">PROJECTED ATTENDANCE</span><div className="projection-number">{projected.toFixed(1)}<small>%</small></div><div className="projection-change">{(projected - current >= 0 ? '+' : '')}{(projected - current).toFixed(1)} percentage points</div><div className="projection-compare"><div><span>Current</span><b>{current.toFixed(1)}%</b></div><div><span>Plan</span><b>Attend {attend} · Miss {miss}</b></div></div><div className="threshold-check"><span className={projected >= 75 ? 'check-on' : 'check-off'}>{projected >= 75 ? <Check size={14} /> : <X size={14} />} 75% {projected >= 75 ? 'safe' : 'danger'}</span><span className={projected >= 90 ? 'check-on' : 'check-off'}>{projected >= 90 ? <Check size={14} /> : <X size={14} />} 90% {projected >= 90 ? 'reached' : 'not reached'}</span></div><p className="projection-note">{afterRemaining < 0 ? 'This plan exceeds the scheduled classes remaining.' : `After this plan, ${afterRemaining} scheduled classes remain for ${subject.name}.`}</p></div></div></div>; }
function LeaveSimulator({ section, records, today }: any) { const [start, setStart] = useState(today); const [end, setEnd] = useState(addDays(today, 2)); const [mode, setMode] = useState<'absence' | 'attended' | 'excluded'>('absence'); const classes = getClassesBetweenDates(section, start <= end ? start : end, start <= end ? end : start); const bySubject = section.subjects.map((subject: any) => ({ subject, affected: classes.filter((item) => item.subject.code === subject.code).length })).filter((item: any) => item.affected); const before = overallRecord(section.subjects, records); const after = section.subjects.reduce((total: any, subject: any) => { const record = records[subject.code] ?? { attended: 0, conducted: 0 }; const count = classes.filter((item) => item.subject.code === subject.code).length; return { attended: total.attended + record.attended + (mode === 'attended' ? count : 0), conducted: total.conducted + record.conducted + (mode === 'excluded' ? 0 : count) }; }, { attended: 0, conducted: 0 }); return <div><div className="section-row"><div><p className="eyebrow">OD / MEDICAL LEAVE</p><h2>Simulate planned leave</h2><p className="muted">Affected classes come from the real timetable, not day counts. Policy treatment is configurable for this simulation.</p></div><span className="policy-note">Default: counts absent</span></div><div className="leave-layout"><div className="panel form-panel"><label>Leave type<select><option>Medical leave</option><option>OD</option></select></label><div className="two-fields"><label>Start date<input type="date" value={start} min={semester.startDate} max={semester.endDate} onChange={(e) => setStart(e.target.value)} /></label><label>End date<input type="date" value={end} min={semester.startDate} max={semester.endDate} onChange={(e) => setEnd(e.target.value)} /></label></div><label>Treatment<select value={mode} onChange={(e) => setMode(e.target.value as typeof mode)}><option value="absence">Counts as absent</option><option value="attended">Counts as attended</option><option value="excluded">Excluded from denominator</option></select></label></div><div className="panel leave-result"><div className="leave-result-top"><div><span className="eyebrow">AFFECTED CLASSES</span><strong>{classes.length}</strong><span>{dateLabel(start)} – {dateLabel(end)}</span></div><div><span className="eyebrow">OVERALL IMPACT</span><strong>{before.conducted ? percentage(before.attended, before.conducted).toFixed(1) : '—'}% <ChevronRight size={17} /> {after.conducted ? percentage(after.attended, after.conducted).toFixed(1) : '—'}%</strong></div></div>{bySubject.length ? bySubject.map((item: any) => <div className="affected-row" key={item.subject.code}><span>{item.subject.name}</span><b>{item.affected} {item.affected === 1 ? 'class' : 'classes'}</b></div>) : <Empty text="No classes are scheduled during this leave period." />}</div></div></div>; }
function Analytics({ section, metrics, overallPct, overall }: any) { const max = Math.max(1, ...metrics.map((item: any) => item.metric.percentage)); return <div><div className="analytics-head"><div><p className="eyebrow">ANALYTICS</p><h2>See the shape of your semester</h2></div><div className="analytics-total"><span>Overall</span><b>{overall.conducted ? overallPct.toFixed(1) : '—'}%</b></div></div><div className="analytics-grid"><div className="panel chart-panel"><div className="panel-title"><div><b>Subject comparison</b><span>Current attendance against 75% threshold</span></div><BarChart3 size={19} /></div><div className="bars">{metrics.map(({ subject, metric }: any) => <div className="bar-row" key={subject.code}><span title={subject.name}>{subject.name}</span><div className="bar-track"><div className={`bar-fill ${statusFor(metric.percentage).toLowerCase()}`} style={{ width: `${Math.min(100, metric.percentage / max * 100)}%` }} /><i style={{ left: `${75 / max * 100}%` }} /></div><b>{metric.conducted ? `${metric.percentage.toFixed(1)}%` : '—'}</b></div>)}</div><div className="chart-legend"><span><i className="legend-dot green" /> Safe ≥90%</span><span><i className="legend-dot amber" /> Caution 75–89%</span><span><i className="legend-dot red" /> Danger &lt;75%</span></div></div><div className="panel distribution-panel"><div className="panel-title"><div><b>Health distribution</b><span>Subjects by current status</span></div><Activity size={19} /></div><div className="donut" style={{ '--safe': `${metrics.filter((x: any) => statusFor(x.metric.percentage) === 'SAFE').length / Math.max(1, metrics.length) * 100}%`, '--caution': `${metrics.filter((x: any) => statusFor(x.metric.percentage) === 'CAUTION').length / Math.max(1, metrics.length) * 100}%` } as React.CSSProperties}><div><b>{metrics.length}</b><span>subjects</span></div></div><div className="distribution-list">{(['SAFE', 'CAUTION', 'DANGER'] as const).map((status) => <div key={status}><span className={`legend-dot ${status.toLowerCase()}`} />{status}<b>{metrics.filter((x: any) => statusFor(x.metric.percentage) === status).length}</b></div>)}</div></div></div><div className="analytics-note"><Sparkles size={17} /><span><b>Projection note:</b> Maximum achievable attendance assumes every remaining scheduled class is attended. It is a ceiling, not a guarantee.</span></div></div>; }
function Advisor({ messages, question, setQuestion, askAdvisor }: any) { return <div className="advisor-page"><div className="advisor-intro"><div className="advisor-orb"><Sparkles size={30} /></div><div><p className="eyebrow">LIVE STATE ASSISTANT</p><h2>AI Attendance Advisor</h2><p>Ask questions in plain language. Answers use your selected section, attendance counts, and deterministic class calculations.</p></div></div><div className="advisor-thread">{messages.length === 0 ? <div className="advisor-welcome"><b>What would you like to know?</b><div className="advisor-prompts">{['Can I miss tomorrow?', 'How many classes can I miss?', 'Can I reach 90%?', 'Show my risky subjects'].map((prompt) => <button key={prompt} onClick={() => askAdvisor(prompt)}>{prompt}<ChevronRight size={15} /></button>)}</div></div> : messages.map((message: any, index: number) => <div className={`thread-message ${message.from}`} key={index}><span>{message.from === 'advisor' ? 'Advisor' : 'You'}</span><p>{message.text}</p></div>)}<div className="advisor-composer"><input value={question} onChange={(e) => setQuestion(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && askAdvisor(question)} placeholder="Ask about your attendance..." /><button onClick={() => askAdvisor(question)}><ChevronRight size={19} /></button></div></div></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><b>{value}</b></div>; }
function Empty({ text }: { text: string }) { return <div className="empty"><CalendarDays size={18} /><span>{text}</span></div>; }
function viewTitle(view: View) { return ({ dashboard: 'Your attendance, at a glance', timetable: 'Your weekly timetable', calculator: 'The numbers behind your plan', simulator: 'Test a different outcome', leave: 'Plan leave with precision', analytics: 'A clearer view of your health', advisor: 'Your personal attendance advisor' })[view]; }
function viewSubtitle(view: View, section: Section, before: boolean, after: boolean) { if (view === 'dashboard') return `${section.displayName} · ${section.venue ?? 'Venue not specified'} · ${before ? 'Semester not started' : after ? 'Semester ended' : `Semester ends ${dateLabel(semester.endDate)}`}`; return ({ timetable: 'Every class is taken from the supplied timetable dataset.', calculator: 'Know exactly what you must attend and what you can safely miss.', simulator: 'Explore scenarios before they affect your real plan.', leave: 'Count actual scheduled classes inside any date range.', analytics: 'Only your entered attendance and real timetable data appear here.', advisor: 'Numerical answers come from the same engine as your dashboard.' })[view]; }
function advisorAnswer(question: string, section: Section, records: AttendanceMap, remaining: ClassInstance[], today: string): string { const lower = question.toLowerCase(); const overall = overallRecord(section.subjects, records); if (lower.includes('risky') || lower.includes('risk') || lower.includes('danger')) { const risky = section.subjects.map((subject) => ({ subject, metric: metricFor(records[subject.code] ?? { attended: 0, conducted: 0 }, remaining.filter((item) => item.subject.code === subject.code).length) })).filter((item) => item.metric.percentage < 75); return risky.length ? `Currently below the 75% threshold: ${risky.map((item) => `${item.subject.name} (${item.metric.percentage.toFixed(1)}%)`).join(', ')}. Review the calculator for exact recovery requirements.` : 'None of your entered subjects are below 75% right now. Keep an eye on subjects in the caution range.'; } if (lower.includes('tomorrow')) { const tomorrow = addDays(today, 1); const classes = getClassesBetweenDates(section, tomorrow, tomorrow); if (!classes.length) return `There are no scheduled classes for ${dateLabel(tomorrow)} in ${section.code}.`; return `Tomorrow has ${classes.length} scheduled ${classes.length === 1 ? 'class' : 'classes'}: ${classes.map((item) => item.subject.name).join(', ')}. To model missing them, use What-If with the affected subject and class count.`; } const target = lower.includes('90') ? 90 : 75; const found = section.subjects.map((subject) => ({ subject, metric: metricFor(records[subject.code] ?? { attended: 0, conducted: 0 }, remaining.filter((item) => item.subject.code === subject.code).length) })).filter((item) => lower.includes(item.subject.name.toLowerCase()) || lower.includes(item.subject.code.toLowerCase())); if (found.length) { const item = found[0]; return `${item.subject.name} is currently ${item.metric.conducted ? `${item.metric.percentage.toFixed(1)}%` : 'not yet entered'}. There are ${item.metric.remaining} scheduled classes remaining. At ${target}%, you need to attend ${target === 90 ? item.metric.required90 : item.metric.required75} of them; ${target === 90 ? item.metric.recovery90 ? 'the target is reachable' : 'the target is unreachable' : item.metric.recovery75 ? 'recovery is possible' : 'recovery is impossible'}.`; } if (lower.includes('reach') || lower.includes('miss') || lower.includes('how many')) { return `Across ${section.displayName}, you have ${remaining.length} scheduled classes remaining. Your entered overall attendance is ${overall.conducted ? `${percentage(overall.attended, overall.conducted).toFixed(1)}%` : 'not available yet'}. Select a subject or open the calculator for exact safe-absence limits.`; } return 'I can answer questions about your selected section, tomorrow’s classes, risky subjects, safe absences, and 75% or 90% recovery. For exact results, enter attended and conducted counts on the dashboard.'; }
export default App;
